import { Review } from './types';

export const translations: { [lang: string]: { [key: string]: string } } = {
  en: {
    bookNowNav: 'Book Now',
    heroSubtitle: 'Honest, reliable auto repair services at prices you can afford. Get an instant discount by booking your appointment online today.',
    heroOffer: '<strong>Limited Time:</strong> Get up to <strong>$100 OFF</strong> your service!',
    heroCTA: 'Claim My Discount Now',
    ctaUrgency: 'Offer expires soon. Limited spots available.',
    dragSlider: 'Drag the slider to see how much you can save.',
    repairCost: 'Repair Cost',
    youSave: 'You Save',
    finalCost: 'Final Cost',
    oilChangeNote: '*Excludes oil changes.',
    detailsApply: 'Details apply. Click for more.',
    couponTitle: 'A Coupon That Actually Saves You Money',
    couponSubtitle: 'We believe in transparent pricing. The more you need, the more you save. It’s that simple.',
    couponList1: `<li>✅ Brakes & Rotors</li><li>✅ A/C Repair</li><li>✅ Engine Diagnostics</li>`,
    couponList2: `<li>✅ Suspension Work</li><li>✅ Transmission Service</li><li>✅ And much more...</li>`,
    couponExclusions: 'Discount applies to labor costs and most parts. Cannot be combined with other offers. Excludes tires and battery replacements.',
    bonusStackTitle: 'PLUS: Get These Bonuses FREE',
    bonusStackSubtitle: 'When you book today, you also get these valuable extras to keep your car running smoothly.',
    bonus1Title: 'FREE Tire Rotation',
    bonus1Desc: 'A $35 value. Promotes even tire wear and extends their life.',
    bonus2Title: 'FREE Brake Inspection',
    bonus2Desc: 'A $50 value. We\'ll check your pads, rotors, and fluid for your safety.',
    bonus3Title: 'FREE Fluid Top-Off',
    bonus3Desc: 'A $25 value. We\'ll top off your essential fluids (washer, coolant, etc).',
    bonusStackDisclaimer: 'Bonuses are provided with any repair service over $100. Must mention this offer at time of booking.',
    step1Title: 'Book Online',
    step1Desc: 'Fill out our secure form with your vehicle info and preferred time.',
    step2Title: 'Drop Off Your Car',
    step2Desc: 'Bring your vehicle to our clean, professional shop at your appointment time.',
    step3Title: 'Save Instantly',
    step3Desc: 'We apply your discount directly to your final bill. No hassle, just savings.',
    testimonialsTitle: 'Trusted by Hundreds of Local Drivers',
    testimonialsSubtitle: 'See what your neighbors are saying about our service.',
    readMore: 'Read More',
    readLess: 'Read Less',
    loadMore: 'Load More Reviews',
    aboutUs: 'ABOUT US',
    aboutTitle: 'Your Friendly Neighborhood Auto Experts',
    aboutBody: 'Since 2005, Queens Auto Service has been the go-to repair shop for drivers in the Algonquin area. We\'re a family-owned business dedicated to providing honest advice, quality workmanship, and fair prices. We treat your car like it\'s our own.',
    aboutTagline: '"The best mechanics in town! Honest, reliable, and fair." - A Happy Customer',
    aboutImageAlt: 'Front view of the Queens Auto Services shop in Algonquin',
    address: '1234 Repair Lane, Algonquin, IL 60102',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'What services do you offer?',
    faq1A: 'We are a full-service auto repair shop. We handle everything from routine maintenance like oil changes and tire rotations to complex engine diagnostics, transmission repairs, brake services, A/C work, and much more.',
    faq2Q: 'Do you work on all makes and models?',
    faq2A: 'Yes, our certified technicians are experienced with a wide variety of domestic and imported vehicles, including cars, trucks, and SUVs.',
    faq3Q: 'Is this discount offer legitimate?',
    faq3A: 'Absolutely. We offer this discount to first-time online customers as a way to earn your trust and business. The savings are applied directly to your invoice.',
    faq4Q: 'Do I need an appointment?',
    faq4A: 'While we sometimes accept walk-ins, we highly recommend booking an appointment online to secure your spot and your discount. This ensures we can give your vehicle the attention it deserves without long wait times.',
    serviceAreaTitle: 'Proudly Serving Algonquin & Surrounding Areas',
    serviceAreaSubtitle: 'Your trusted local mechanic is just a short drive away.',
    mapImageAlt: 'Map showing service area for Queens Auto Services',
    serviceAreaList: 'Including: Lake in the Hills, Crystal Lake, Huntley, Carpentersville, and Cary.',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    fullAddress: '1234 Repair Lane, Algonquin, IL 60102',
    modalTitle: 'Discount Offer Details',
    modalP1: 'The discount is calculated based on the total pre-tax cost of your repair or service order.',
    modalP2: 'Discount tiers are as follows: Spend $100+, save $15. Spend $200+, save $30. Spend $300+, save $40. Spend $500+, save $50. Spend $700+, save $100.',
    modalP3: 'This offer cannot be combined with any other promotions. It is not applicable to tire purchases, battery replacements, or state inspection fees. Offer valid for new customers booking through this website only.',
    popupTitleV2: "Wait! Don't Leave Empty-Handed",
    popupSubtitleV2: "Book now and we'll add a FREE oil change to your order!",
    popupBonus1: 'Up to <strong>$100 OFF</strong> your repair',
    popupBonus2: 'FREE Tire Rotation',
    popupBonus3: 'FREE Brake Inspection',
    popupBonus4: 'FREE Fluid Top-Off',
    popupBonus5: '<strong class="text-cyan-400">PLUS A FREE OIL CHANGE!</strong>',
    popupCTAV2: 'Claim All My Bonuses!',
    formInstruction1: 'Tell us about you and your vehicle.',
    formInstruction2: 'Choose a date and time that works for you.',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email Address',
    mobileNumber: 'Mobile Number',
    vehicleDetails: 'Vehicle Details',
    carYear: 'Year',
    carMake: 'Make',
    carModel: 'Model',
    nextButton: 'Next: Choose Date & Time &rarr;',
    whenBringIn: 'When would you like to bring your car in?',
    availableTimes: 'Available Times for Your Selected Date',
    backButton: '&larr; Back to Details',
    submitBtn: 'Book My Appointment!',
    bookingSuccess: 'Booking...',
    thankYouTitle: 'You\'re All Set, {{name}}!',
    playingAudio: 'Playing...',
    playAgain: 'Play Again',
    playMessageFor: 'Play Message for {{name}}',
    yourCouponCodeIs: 'Your coupon code is:',
    copied: 'Copied!',
    confirmationText1: 'Your appointment is confirmed. We\'ve sent a confirmation to your email and a text reminder to your phone.',
    confirmationText2: 'Service for your: {{vehicle}}.',
    serviceTitle: 'Service Type',
    serviceValue: 'General Repair / Diagnostics',
    dateTimeTitle: 'Date & Time',

    locationTitle: 'Location',
    locationValue: 'Queens Auto Services',
    whatHappensNextTitle: 'What Happens Next?',
    whatHappensNextStep1: 'You will receive an email confirmation shortly.',
    whatHappensNextStep2: 'A friendly team member will call you if we have any questions.',
    whatHappensNextStep3: 'Bring your vehicle in at your scheduled time and we\'ll take care of the rest!',
    needToRescheduleTitle: 'Need to Reschedule?',
    needToRescheduleBody: 'No problem. Just give us a call.',
    phoneNumber: '(847) 555-1234',
    phoneNumberLink: 'tel:8475551234',
    whereToFindUsTitle: 'Where to Find Us',
    getDirections: 'Get Directions',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=Queens+Auto+Service+Algonquin+IL',
    footerCopyright: '&copy; {{year}} Queens Auto Service. All Rights Reserved.'
  },
  es: {
    bookNowNav: 'Reservar Ahora',
    heroSubtitle: 'Servicios de reparación de automóviles honestos y confiables a precios que puede pagar. Obtenga un descuento instantáneo reservando su cita en línea hoy.',
    heroOffer: '<strong>Oferta por tiempo limitado:</strong> ¡Obtenga hasta <strong>$100 de DESCUENTO</strong> en su servicio!',
    heroCTA: 'Reclamar Mi Descuento Ahora',
    ctaUrgency: 'La oferta expira pronto. Plazas limitadas disponibles.',
    dragSlider: 'Arrastre el control deslizante para ver cuánto puede ahorrar.',
    repairCost: 'Costo de Reparación',
    youSave: 'Usted Ahorra',
    finalCost: 'Costo Final',
    oilChangeNote: '*Excluye cambios de aceite.',
    detailsApply: 'Se aplican detalles. Haga clic para más información.',
    couponTitle: 'Un Cupón Que Realmente Le Ahorra Dinero',
    couponSubtitle: 'Creemos en precios transparentes. Cuanto más necesite, más ahorrará. Es así de simple.',
    couponList1: `<li>✅ Frenos y Rotores</li><li>✅ Reparación de A/C</li><li>✅ Diagnóstico del Motor</li>`,
    couponList2: `<li>✅ Trabajo de Suspensión</li><li>✅ Servicio de Transmisión</li><li>✅ Y mucho más...</li>`,
    couponExclusions: 'El descuento se aplica a los costos de mano de obra y la mayoría de las piezas. No se puede combinar con otras ofertas. Excluye neumáticos y reemplazos de batería.',
    bonusStackTitle: 'ADEMÁS: Obtenga Estos Bonos GRATIS',
    bonusStackSubtitle: 'Cuando reserva hoy, también obtiene estos valiosos extras para mantener su automóvil funcionando sin problemas.',
    bonus1Title: 'Rotación de Llantas GRATIS',
    bonus1Desc: 'Un valor de $35. Promueve el desgaste uniforme de las llantas y extiende su vida útil.',
    bonus2Title: 'Inspección de Frenos GRATIS',
    bonus2Desc: 'Un valor de $50. Revisaremos sus pastillas, rotores y líquido para su seguridad.',
    bonus3Title: 'Relleno de Líquidos GRATIS',
    bonus3Desc: 'Un valor de $25. Rellenaremos sus líquidos esenciales (limpiaparabrisas, refrigerante, etc.).',
    bonusStackDisclaimer: 'Los bonos se proporcionan con cualquier servicio de reparación superior a $100. Debe mencionar esta oferta al momento de la reserva.',
    step1Title: 'Reserve en Línea',
    step1Desc: 'Complete nuestro formulario seguro con la información de su vehículo y la hora preferida.',
    step2Title: 'Deje Su Automóvil',
    step2Desc: 'Traiga su vehículo a nuestro taller limpio y profesional a la hora de su cita.',
    step3Title: 'Ahorre al Instante',
    step3Desc: 'Aplicamos su descuento directamente a su factura final. Sin complicaciones, solo ahorros.',
    testimonialsTitle: 'Con la Confianza de Cientos de Conductores Locales',
    testimonialsSubtitle: 'Vea lo que sus vecinos dicen sobre nuestro servicio.',
    readMore: 'Leer Más',
    readLess: 'Leer Menos',
    loadMore: 'Cargar Más Reseñas',
    aboutUs: 'SOBRE NOSOTROS',
    aboutTitle: 'Sus Expertos en Automóviles Amigables del Vecindario',
    aboutBody: 'Desde 2005, Queens Auto Service ha sido el taller de reparación de referencia para los conductores en el área de Algonquin. Somos una empresa familiar dedicada a brindar consejos honestos, mano de obra de calidad y precios justos. Tratamos su automóvil como si fuera nuestro.',
    aboutTagline: '"¡Los mejores mecánicos de la ciudad! Honestos, confiables y justos." - Un Cliente Feliz',
    aboutImageAlt: 'Vista frontal del taller de Queens Auto Services en Algonquin',
    address: '1234 Repair Lane, Algonquin, IL 60102',
    faqTitle: 'Preguntas Frecuentes',
    faq1Q: '¿Qué servicios ofrecen?',
    faq1A: 'Somos un taller de reparación de automóviles de servicio completo. Nos encargamos de todo, desde el mantenimiento de rutina como cambios de aceite y rotaciones de llantas hasta diagnósticos complejos del motor, reparaciones de transmisión, servicios de frenos, trabajo de A/C y mucho más.',
    faq2Q: '¿Trabajan en todas las marcas y modelos?',
    faq2A: 'Sí, nuestros técnicos certificados tienen experiencia con una amplia variedad de vehículos nacionales e importados, incluidos automóviles, camionetas y SUV.',
    faq3Q: '¿Es legítima esta oferta de descuento?',
    faq3A: 'Absolutamente. Ofrecemos este descuento a los clientes que reservan en línea por primera vez como una forma de ganar su confianza y su negocio. Los ahorros se aplican directamente a su factura.',
    faq4Q: '¿Necesito una cita?',
    faq4A: 'Aunque a veces aceptamos clientes sin cita, recomendamos encarecidamente reservar una cita en línea para asegurar su lugar y su descuento. Esto garantiza que podamos darle a su vehículo la atención que merece sin largos tiempos de espera.',
    serviceAreaTitle: 'Sirviendo con Orgullo a Algonquin y Áreas Circundantes',
    serviceAreaSubtitle: 'Su mecánico local de confianza está a poca distancia en automóvil.',
    mapImageAlt: 'Mapa que muestra el área de servicio de Queens Auto Services',
    serviceAreaList: 'Incluyendo: Lake in the Hills, Crystal Lake, Huntley, Carpentersville y Cary.',
    privacyPolicy: 'Política de Privacidad',
    termsOfUse: 'Términos de Uso',
    fullAddress: '1234 Repair Lane, Algonquin, IL 60102',
    modalTitle: 'Detalles de la Oferta de Descuento',
    modalP1: 'El descuento se calcula en función del costo total antes de impuestos de su orden de reparación o servicio.',
    modalP2: 'Los niveles de descuento son los siguientes: Gaste $100+, ahorre $15. Gaste $200+, ahorre $30. Gaste $300+, ahorre $40. Gaste $500+, ahorre $50. Gaste $700+, ahorre $100.',
    modalP3: 'Esta oferta no se puede combinar con ninguna otra promoción. No es aplicable a la compra de llantas, reemplazos de batería o tarifas de inspección estatal. Oferta válida solo para nuevos clientes que reserven a través de este sitio web.',
    popupTitleV2: "¡Espere! No Se Vaya con las Manos Vacías",
    popupSubtitleV2: "¡Reserve ahora y agregaremos un cambio de aceite GRATIS a su pedido!",
    popupBonus1: 'Hasta <strong>$100 de DESCUENTO</strong> en su reparación',
    popupBonus2: 'Rotación de Llantas GRATIS',
    popupBonus3: 'Inspección de Frenos GRATIS',
    popupBonus4: 'Relleno de Líquidos GRATIS',
    popupBonus5: '<strong class="text-cyan-400">¡MÁS UN CAMBIO DE ACEITE GRATIS!</strong>',
    popupCTAV2: '¡Reclamar Todos Mis Bonos!',
    formInstruction1: 'Cuéntenos sobre usted y su vehículo.',
    formInstruction2: 'Elija una fecha y hora que le convenga.',
    firstName: 'Nombre',
    lastName: 'Apellido',
    email: 'Correo Electrónico',
    mobileNumber: 'Número de Móvil',
    vehicleDetails: 'Detalles del Vehículo',
    carYear: 'Año',
    carMake: 'Marca',
    carModel: 'Modelo',
    nextButton: 'Siguiente: Elegir Fecha y Hora &rarr;',
    whenBringIn: '¿Cuándo le gustaría traer su automóvil?',
    availableTimes: 'Horarios Disponibles para la Fecha Seleccionada',
    backButton: '&larr; Volver a Detalles',
    submitBtn: '¡Reservar Mi Cita!',
    bookingSuccess: 'Reservando...',
    thankYouTitle: '¡Todo Listo, {{name}}!',
    playingAudio: 'Reproduciendo...',
    playAgain: 'Reproducir de Nuevo',
    playMessageFor: 'Reproducir Mensaje para {{name}}',
    yourCouponCodeIs: 'Su código de cupón es:',
    copied: '¡Copiado!',
    confirmationText1: 'Su cita está confirmada. Hemos enviado una confirmación a su correo electrónico y un recordatorio por mensaje de texto a su teléfono.',
    confirmationText2: 'Servicio para su: {{vehicle}}.',
    serviceTitle: 'Tipo de Servicio',
    serviceValue: 'Reparación General / Diagnóstico',
    dateTimeTitle: 'Fecha y Hora',
    locationTitle: 'Ubicación',
    locationValue: 'Queens Auto Services',
    whatHappensNextTitle: '¿Qué Sigue?',
    whatHappensNextStep1: 'Recibirá una confirmación por correo electrónico en breve.',
    whatHappensNextStep2: 'Un miembro amable del equipo lo llamará si tenemos alguna pregunta.',
    whatHappensNextStep3: '¡Traiga su vehículo a la hora programada y nosotros nos encargaremos del resto!',
    needToRescheduleTitle: '¿Necesita Reprogramar?',
    needToRescheduleBody: 'No hay problema. Solo llámenos.',
    phoneNumber: '(847) 555-1234',
    phoneNumberLink: 'tel:8475551234',
    whereToFindUsTitle: 'Dónde Encontrarnos',
    getDirections: 'Obtener Direcciones',
    googleMapsLink: 'https://www.google.com/maps/search/?api=1&query=Queens+Auto+Service+Algonquin+IL',
    footerCopyright: '&copy; {{year}} Queens Auto Service. Todos los derechos reservados.'
  },
};

export const testimonials: Review[] = [
  { name: 'John D.', text: 'Absolutely fantastic service. They diagnosed the issue with my car quickly and the repair cost was very reasonable. The discount I got from booking online was the cherry on top. Highly recommend!' },
  { name: 'Maria S.', text: 'I was hesitant to try a new mechanic, but Queens Auto Service exceeded my expectations. They were professional, courteous, and transparent about the work needed. My car runs like new again. I will definitely be back.' },
  { name: 'David L.', text: 'Honest and reliable. They didn\'t try to upsell me on services I didn\'t need. The final price was exactly what they quoted. It\'s great to find a mechanic you can trust.' },
  { name: 'Sarah P.', text: 'The online booking process was super easy. I picked a time that worked for me, dropped off my car, and they had it ready when they said they would. The free brake inspection gave me peace of mind.' },
  { name: 'Mike Johnson', text: 'Great experience from start to finish. Friendly staff, clean waiting area, and top-notch work. They even explained the repairs to me in a way I could understand. I\'m very impressed.' },
  { name: 'Emily Chen', text: 'I saved $100 on a major repair just by finding their website. The service was excellent and my car is running perfectly. I couldn\'t be happier. I\'ve already recommended them to my friends and family.' },
  { name: 'Robert B.', text: 'I\'ve been going to Queens Auto for years. They always do a great job. This new online offer is just another reason why they\'re the best in the area. They truly care about their customers.' },
  { name: 'Jessica W.', text: 'They fixed a persistent A/C problem that another shop couldn\'t figure out. The technicians are clearly very knowledgeable. The online discount made it even better. Thank you, Queens Auto!' },
  { name: 'Tom H.', text: 'Fair prices and excellent customer service. What more could you ask for? They kept me updated throughout the repair process. A very professional operation.' }
];

export const faqData = [
  { qKey: 'faq1Q', aKey: 'faq1A' },
  { qKey: 'faq2Q', aKey: 'faq2A' },
  { qKey: 'faq3Q', aKey: 'faq3A' },
  { qKey: 'faq4Q', aKey: 'faq4A' },
];

export const bonusData = [
    { icon: 'rotate-cw', titleKey: 'bonus1Title', descKey: 'bonus1Desc' },
    { icon: 'shield-check', titleKey: 'bonus2Title', descKey: 'bonus2Desc' },
    { icon: 'droplets', titleKey: 'bonus3Title', descKey: 'bonus3Desc' },
];
